### ISSUE TITLE
request to contribute

### ISSUE THREAD

**Issue by ekraj218** [theonlyNischal/Ultimate-Notes-Books-Resources-for-NCIT#24]
i want to add some files that i have.

**Comment by theonlyNischal** [comment]
Hi @ekraj218, Thank you so much.

Please upload the resources in your fork situated at [https://github.com/ekraj218/Ultimate-Notes-Books-Resources-for-NCIT](https://github.com/ekraj218/Ultimate-Notes-Books-Resources-for-NCIT) and make a pull request at this repo.

**Comment by theonlyNischal** [comment]
Inactive issue.
