### ISSUE TITLE
Some pdf inside ELX 230_Microprocessors are password protected

### ISSUE THREAD

**Issue by PR7JW7L** [theonlyNischal/Ultimate-Notes-Books-Resources-for-NCIT#65]

**Comment by PranavBhattarai** [comment]
I solution I found toward this problem:

`rm -rf <locked-pdf-name>`

This really do the magic by saving us a lot of time.

**Comment by theonlyNischal** [comment]
@ekraj218 Have you got the password for those pdf files?

**Comment by theonlyNischal** [comment]
Nec013 is the password. Please try this.
